### PR TITLE
don't try to render unsupported view models

### PR DESCRIPTION
**Pull request by countless-integers**
one more go at #13 for the sake of ppl that don't want to switch to another module

### CODE REVIEW

**Comment by seyfer** [comment]
:+1: need merge

**Comment by countless-integers** [comment]
doesn't look like it's happening. Honestly I can't find a smarty module for zf2 that would be actively maintained.

**Comment by MurgaNikolay** [comment]
Hi guys.
I went to Ruby and, unfortunately, I am unable to keep my PHP projects :(

**Comment by countless-integers** [comment]
Thanks! Wish I could switch languages too :smile:

**Pull request merged**
